from . import iso_action
from . import iso_audit
from . import iso_document
from . import iso_indicator
from . import iso_complaint
from . import iso_risk
from . import iso_regulation
from . import res_partner
from . import hr_employee
